#!/bin/bash

# Function to install dependencies
install_dependencies() {
    echo 'Installing dependencies...'
    if ! pip install --user -r requirements.txt; then
        echo "Error installation requirements"
        return 1
    fi
    if ! npm install -g typescript; then
        echo "Error installing typescript"
        return 1
    fi
    if ! npm install -g yarn; then
        echo "Error installing yarn"
        return 1
    fi
    if ! npm install @octokit/rest; then
        echo "Error installing octokit/rest"
        return 1
    fi
    if ! yarn add @octokit/rest; then
        echo "Error adding octokit/rest"
        return 1
    fi
    
    return 0
}

# Check if the command is 'install'
if [ "$#" -ne 1 ]; then
    echo "Usage: ./run install"
    exit 1
fi

command=$1

if [ "$command" = "install" ]; then
    install_dependencies
    exit $?
elif [ "$command" = "build" ]; then
    tsc.cmd src/urlhandler.ts
    node src/urlhandler.js
    exit $?
else
    echo command: $command
    exit 1
fi
