#!/bin/bash

# Function to install dependencies
install_dependencies() {
    echo 'Installing dependencies...'
    if ! pip install --user -r requirements.txt; then
        echo "Error during installation"
        return 1
    fi
    return 0
}

# Check if the command is 'install'
if [ "$#" -ne 1 ]; then
    echo "Usage: ./run install"
    exit 1
fi

command=$1

if [ "$command" = "install" ]; then
    install_dependencies
    exit $?
elif [ "$command" = "build" ]; then
    tsc.cmd src/urlhandler.ts
    node src/urlhandler.js
    exit $?
else
    echo "Unknown command: $command"
    exit 1
fi
